package com.masomohigh.model;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Created by Kevin Kimaru Chege on 12/10/2017.
 */
@IdClass(ClassKey.class)
@Entity
public class Class implements Serializable {
    private static final long serialVersionUID = 4685631589912848921L;

    @Id
    @GeneratedValue
    protected int classId;
    @Id
    @Column(unique = true)
    protected String name;
    protected String stream;
    protected int form;
    //teacher term
    @OneToMany
    protected List<Teacher> classTeachers;
    protected int classYear;
    @ManyToMany
    protected Map<String, List<Teacher>> subjectTeachers;
    @ManyToMany(mappedBy = "classes")
    protected List<Student> students;

    public Class() {}

    /**
     * Missing: classId, classTeachers, subjectTeachers, students
     * Name is autogenerated
     * */
    public Class(String stream, int form, int classYear) {
        this.stream = stream;
        this.form = form;
        this.classYear = classYear;
        this.name = form + stream + classYear;
        classTeachers = new ArrayList<>();
        students = new ArrayList<>();
    }

    public int getClassId() {
        return classId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getStream() {
        return stream;
    }

    public void setStream(String stream) {
        this.stream = stream;
    }

    public int getForm() {
        return form;
    }

    public void setForm(int form) {
        this.form = form;
    }

    public List<Teacher> getClassTeachers() {
        return classTeachers;
    }

    public void setClassTeachers(List<Teacher> classTeachers) {
        this.classTeachers = classTeachers;
    }

    public int getClassYear() {
        return classYear;
    }

    public void setClassYear(int classYear) {
        this.classYear = classYear;
    }

    public Map<String, List<Teacher>> getSubjectTeachers() {
        return subjectTeachers;
    }

    public void setSubjectTeachers(Map<String, List<Teacher>> subjectTeachers) {
        this.subjectTeachers = subjectTeachers;
    }

    public List<Student> getStudents() {
        return students;
    }

    public void setStudents(List<Student> students) {
        this.students = students;
    }
}
